version: '3.9'

services:
  userservice:
    build:
      context: .
      dockerfile: UserServiceAPI/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - PRODUCTSERVICE_URL=http://productservice:8080
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"] # Пример проверки здоровья
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  productservice:
    build:
      context: .
      dockerfile: ProductServiceAPI/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"] 
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

networks:
  app_network:
    driver: bridge
